healthmate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('appointment/', include('appointment.urls')),
    path('consult/', include('videoapp.urls')),
    path('checkout/', include('orders.urls')),
    path('labs/', include('labs.urls')),
    path('adminapp/', include('adminapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.booking_test, name='booking_test'),
    path('ajax/get_test_details/', views.get_test_details, name='get_test_details'),
]

labs/models.py
from django.db import models
from accounts.models import PatientProfile, City

# Create your models here.

class LabTest(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255, null=True)
    image = models.ImageField(blank=True, upload_to='lab_test_images')
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class LabTestBooking(models.Model):
    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    lab_test = models.ForeignKey(LabTest, on_delete=models.CASCADE)
    booking_date = models.DateField(auto_now_add=True)
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    phone_number = models.CharField(max_length=12)
    remarks = models.CharField(max_length=255, null=True)
    status = models.CharField(max_length=20, default='pending')
    address = models.CharField(max_length=255)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    zip_code = models.CharField(max_length=20)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    def order_id(self):
        try:
            from orders.models import Order
            order = Order.objects.get(lab=self)
            return order.id
        except:
            return 0


class PendingLabBooking(models.Model):
    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    lab_test = models.ForeignKey(LabTest, on_delete=models.CASCADE)
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    phone_number = models.CharField(max_length=12)
    address = models.CharField(max_length=255)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    zip_code = models.CharField(max_length=20)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True)

labs/forms.py
from django import forms
from .models import LabTestBooking, LabTest
from django.utils import timezone

class LabTestBookingForm(forms.ModelForm):
    appointment_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date", "class": "form-control", "min": timezone.now().date()}))
    appointment_time = forms.TimeField(widget=forms.TextInput(attrs={"type": "time", "class": "form-control",}))
    class Meta:
        model = LabTestBooking
        fields = ['lab_test', 'appointment_date', 'appointment_time', 'full_name', 'phone_number', 'address', 'city', 'zip_code']

    def __init__(self, *args, **kwargs):
        super(LabTestBookingForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class LabTestForm(forms.ModelForm):
    class Meta:
        model = LabTest
        fields = ['name', 'description', 'image', 'price']

    def __init__(self, *args, **kwargs):
        super(LabTestForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

labs/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import LabTest
from .forms import LabTestBookingForm
from django.http import JsonResponse

# Create your views here.

@login_required(login_url='login')
def booking_test(request):
    lab_form = LabTestBookingForm()
    context = {
        'lab_form': lab_form,
    }
    return  render(request, 'labs/booking_test.html', context)


def get_test_details(request):
    lab_test_id = request.GET.get('lab_test_id')
    if lab_test_id:
        lab_test = LabTest.objects.get(id=lab_test_id)
        test_details = {'id': lab_test.id, 'name': lab_test.name, 'description': lab_test.description, 'image': lab_test.image.url, 'price':lab_test.price}
        return JsonResponse(test_details)
    return JsonResponse({'error': 'Invalid request'})

templates/labs/booking_test.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Breadcrumb -->
<div class="breadcrumb-bar">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-12 col-12">
                <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Booking Lab Test</li>
                    </ol>
                </nav>
                <h2 class="breadcrumb-title">Booking Lab Test</h2>
            </div>
        </div>
    </div>
</div> 
<!-- /Breadcrumb -->

<!-- Page Content -->
<div class="content">
    <div class="container">   
        <div class="row">

            <div class="col-md-5 col-lg-4 theiaStickySidebar">						
                <div class="card flex-fill">
                    <img alt="Card Image" src="{% static 'assets/img/features/lab.jpg' %}" class="card-img-top" style="height: 100%;">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Book sample collection from home</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">safe, secure & private</p>
                    </div>
                    <div class="card-footer text-muted">
                        Book affordable lab tests from your home.
                    </div>
                </div>                
            </div>

            <div class="col-md-7 col-lg-8">
                <div class="card">
                    <div class="card-body">
                    
                        <div class="card-title">
                            <h3>Book A Home Visit</h3>
                            <p style="color:grey;">
                                We are continually harnessing our medical expertise to build best test offering while investing in technology to transform the delivery of health care.
                            </p>
                        </div>
                        
                        <!-- Checkout Form -->
                        <form action="{% url 'lab_checkout' %}" method="POST">
                        {% csrf_token %}  
                            <!-- Booking Information -->
                            <h4 class="card-title">Booking Details</h4>
                            <div class="row">
                                <div class="col-md-6 col-sm-12">
                                    <div class="form-group card-label">
                                        <label> Select Service</label>
                                        {{lab_form.lab_test}}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <div class="form-group card-label">
                                        <label>City</label>
                                        {{lab_form.city}}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <div class="form-group card-label">
                                        <label>Date</label>
                                        {{lab_form.appointment_date}}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <div class="form-group card-label">
                                        <label>Time</label>
                                        {{lab_form.appointment_time}}
                                    </div>
                                </div>
                            </div>
                            <!-- /Booking Information -->

                            <!-- Personal Information -->
                            <h4 class="card-title">Personal Information</h4>
                            <div class="row">
                                <div class="col-md-6 col-sm-12">
                                    <div class="form-group card-label">
                                        <label>Full Name</label>
                                        {{lab_form.full_name}}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <div class="form-group card-label">
                                        <label>Phone</label>
                                        {{lab_form.phone_number}}
                                    </div>
                                </div>
                                <div class="col-md-12 col-sm-12">
                                    <div class="form-group card-label">
                                        <label>Street address</label>
                                        {{lab_form.address}}
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <div class="form-group card-label">
                                        <label>Zip Code</label>
                                        {{lab_form.zip_code}}
                                    </div>
                                </div>
                            </div>
                            <!-- /Personal Information -->
                                                            
                            <!-- Submit Section -->
                            <div class="submit-section mt-4">
                                <button type="submit" class="btn btn-info submit-btn" style="width:100%">Book your visit</button>
                            </div>
                            <!-- /Submit Section -->
                                
                        </form>
                        <!-- /Checkout Form -->
                        
                    </div>
                </div>                
            </div>

        </div>
    </div>
</div>
<!-- /Page Content -->

{% include 'includes/footer.html' %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#id_lab_test').change(function () {  // Change to match the actual ID of your country select input
            var labTestId = $(this).val();
            $.ajax({
                url: '{% url "get_test_details" %}',
                data: { 'lab_test_id': labTestId },
                dataType: 'json',
                success: function (data) {
                    if (data) {
                        $('.card-img-top').attr('src', data.image);
                        $('.card-header h5').text(data.name);  
                        $('.card-text').text(data.description);
                        $('.card-footer').text('₹ ' + data.price);  // Update lab test price
                        // Add other details as needed
                    } else {
                        console.error('Error: Test details not found');
                    }
                }
            });
        });
    });
</script>
{% endblock %}

templates/labs/my_labs.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Breadcrumb -->
<div class="breadcrumb-bar">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-12 col-12">
                <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                    </ol>
                </nav>
                <h2 class="breadcrumb-title">Dashboard</h2>
            </div>
        </div>
    </div>
</div>
<!-- /Breadcrumb -->

<!-- Page Content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">            
            {% include 'includes/patient_sidebar.html' %}
            <div class="col-md-7 col-lg-8 col-xl-9">
            <div class="row">
                {% include 'includes/alerts.html' %}
                <div class="col-md-12"><h2 class="mb-4">Lab Appoinments</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-hover table-center mb-0">
                            <thead>
                                <tr>
                                    <th>Lab Test</th>
                                    <th>Appt Date</th>
                                    <th>Booking Date</th>
                                    <th>Status</th>
                                    <th class="text-right">View Invoice</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for lab in labs%}
                                <tr>
                                    <td>
                                        <h2 class="table-avatar">
                                            <a href="" class="avatar avatar-sm mr-2">
                                                <img class="avatar-img rounded-circle" src="{{lab.lab_test.image.url}}" alt="User">
                                            </a>
                                            <a href="">{{lab.lab_test.name}}
                                            </a>
                                        </h2>
                                    </td>
                                    <td>{{lab.appointment_date}}<span class="d-block text-info">{{lab.appointment_time}}</span></td>
                                    <td>{{lab.booking_date}}</td>
                                    <td>
                                        {% if lab.status == 'confirmed' or lab.status == 'complete' %}
                                            <span class="badge badge-pill bg-success-light">{{ lab.status }}</span>
                                        {% elif lab.status == 'pending' %}
                                            <span class="badge badge-pill bg-warning-light">{{ lab.status }}</span>
                                        {% elif lab.status == 'cancelled' %}
                                            <span class="badge badge-pill bg-danger-light">{{ lab.status }}</span>
                                        {% endif %}
                                    </td>
                                    <td class="text-right">
                                        <div class="table-action">
                                            <a href="{% url 'view_invoice' lab.order_id %}" class="btn btn-sm bg-info-light" target="_blank">
                                                <i class="far fa-eye"></i> View
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>

{% include 'includes/footer.html' %}
{% endblock %}