adminapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # post views
    path('', views.index, name='index'),
    path('register/', views.adminapp_register, name='adminapp_register'),
    path('login/', views.adminapp_login, name='adminapp_login'),
    path('logout/', views.adminapp_logout, name='adminapp_logout'),
    path('profile/', views.adminapp_profile, name='adminapp_profile'),
    path('change_password/', views.adminapp_change_password, name='adminapp_change_password'),
    path('doctor_list/', views.adminapp_doctor_list, name='adminapp_doctor_list'),
    path('patient_list/', views.adminapp_patient_list, name='adminapp_patient_list'),
    path('ajax/change_status/', views.change_status, name='change_status'),
    path('specialities/', views.adminapp_specialities, name='adminapp_specialities'),
    path('delete_specialization/', views.delete_specialization, name='delete_specialization'),
    path('edit_specialization/', views.edit_specialization, name='edit_specialization'),
    path('reviews/', views.adminapp_reviews, name='adminapp_reviews'), 
    path('delete_review/', views.delete_review, name='delete_review'),
    path('transactions/', views.adminapp_transactions, name='adminapp_transactions'),
    path('delete_order/', views.delete_order, name='delete_order'),
    path('lab_appointments/', views.adminapp_lab_appointments, name='adminapp_lab_appointments'),
    path('edit_lab_appointments/<int:id>/', views.edit_lab_appointments, name='edit_lab_appointments'),
    path('add_lab_results/<int:id>/', views.add_lab_results, name='add_lab_results'),
    path('lab_tests/', views.adminapp_lab_tests, name='adminapp_lab_tests'),
    path('delete_lab_tests/', views.delete_lab_tests, name='delete_lab_tests'),
    path('forgotPassword/', views.forgotAdminPassword, name='forgotAdminPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetAdminpassword_validate, name='resetAdminpassword_validate'),
    path('resetPassword/', views.resetAdminPassword, name='resetAdminPassword'),
]

healthmate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('appointment/', include('appointment.urls')),
    path('consult/', include('videoapp.urls')),
    path('checkout/', include('orders.urls')),
    path('labs/', include('labs.urls')),
    path('adminapp/', include('adminapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.booking_test, name='booking_test'),
    path('ajax/get_test_details/', views.get_test_details, name='get_test_details'),
]

adminapp/models.py
from django.db import models

# Create your models here.

labs/models.py
from django.db import models
from accounts.models import PatientProfile, City

# Create your models here.

class LabTest(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255, null=True)
    image = models.ImageField(blank=True, upload_to='lab_test_images')
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class LabTestBooking(models.Model):
    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    lab_test = models.ForeignKey(LabTest, on_delete=models.CASCADE)
    booking_date = models.DateField(auto_now_add=True)
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    phone_number = models.CharField(max_length=12)
    remarks = models.CharField(max_length=255, null=True)
    status = models.CharField(max_length=20, default='pending')
    address = models.CharField(max_length=255)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    zip_code = models.CharField(max_length=20)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    def order_id(self):
        try:
            from orders.models import Order
            order = Order.objects.get(lab=self)
            return order.id
        except:
            return 0


class PendingLabBooking(models.Model):
    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    lab_test = models.ForeignKey(LabTest, on_delete=models.CASCADE)
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    phone_number = models.CharField(max_length=12)
    address = models.CharField(max_length=255)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    zip_code = models.CharField(max_length=20)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True)

adminapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages, auth
from django.contrib.auth.decorators import user_passes_test
from accounts.forms import RegistrationForm, UserForm, MedicalRecordForm
from accounts.models import User, PatientProfile, DoctorProfile, Specialization, ReviewRating, MedicalRecord
from django.http import JsonResponse
from django.utils.text import slugify
from orders.models import Order
from labs.models import LabTestBooking, LabTest
from labs.forms import LabTestForm
from django.db.models import Q
# importing files for verification
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

# Create your views here.

def is_admin(user):
    return user.is_authenticated and user.is_admin


def adminapp_register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            # creating user account
            user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
            user.phone_number = phone_number
            # Now activating user's account
            user.is_active = True
            user.is_admin = True
            user.profile_picture = 'userprofile/Admin_Profile.png'
            user.save()
            messages.success(request, 'Your account has been created successfully.')
            return redirect('adminapp_login')
        else:
            messages.error(request, 'Invalid data.')
            return redirect('adminapp_register')
    else:       
        form = RegistrationForm()
    context = {
        'form':form,
    }
    return render(request, 'adminapp/register.html', context)


@login_required(login_url='adminapp_login')
@user_passes_test(is_admin)
def index(request):
    doc_count = DoctorProfile.objects.count()
    pat_count = PatientProfile.objects.count()
    app_count = Order.objects.count()
    doctors = DoctorProfile.objects.all().order_by('-user__date_joined')[:5]
    patients = PatientProfile.objects.all().order_by('-user__date_joined')[:5]
    context = {
        'doc_count': doc_count,
        'pat_count': pat_count,
        'app_count': app_count,
        'doctors': doctors,
        'patients': patients,
    }
    return render(request, 'adminapp/index.html', context)


def adminapp_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(email=email, password=password)

        if user is not None and user.is_admin:
            auth.login(request, user)
            messages.success(request, 'You are now logged in.')
            return redirect('/adminapp')
        else:
            messages.error(request, 'Invalid login credentials.')
            return redirect('adminapp_login')
    return render(request, 'adminapp/login.html')


@login_required(login_url='adminapp_login')
def adminapp_logout(request):
    auth.logout(request)
    messages.success(request, 'You are logged out.')
    return redirect('adminapp_login')


@login_required(login_url='adminapp_login')
@user_passes_test(is_admin)
def adminapp_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, request.FILES, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('adminapp_profile')
        else:
            messages.error(request, 'Please enter valid data in the form!!')
            return redirect('adminapp_profile')
    else:
        user_form = UserForm(instance=request.user)
    context = {
        'user_form': user_form,
    }  
    return render(request, 'adminapp/profile.html', context)


@login_required(login_url='adminapp_login')
@user_passes_test(is_admin)
def adminapp_change_password(request):
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
 
        user = User.objects.get(username__exact=request.user.username)

        if new_password == confirm_password:
            success = user.check_password(current_password)
            if success:
                '''
                if not re.match(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$', new_password):
                    messages.error(request, "Password should be at least 8 characters and contain a combination of uppercase, lowercase, digits, and special symbols!")
                    return redirect('adminapp_change_password')
                    '''
                user.set_password(new_password)
                user.save()
                
                updated_user = auth.authenticate(email=user.email, password=new_password)
                if updated_user is not None:
                    auth.login(request, updated_user)  # Keep the user logged in
                    messages.success(request, 'Password updated successfully.')
                    return redirect('adminapp_profile')
                else:
                    messages.error(request, 'Failed to re-authenticate after password change.')

                messages.success(request, 'Password updated successfully.')
                return redirect('adminapp_profile')
            else:
                messages.error(request, 'Please enter valid current password')
                return redirect('adminapp_profile')
        else:
            messages.error(request, 'Password does not match!')
            return redirect('adminapp_profile')
        

@login_required(login_url='adminapp_login')
@user_passes_test(is_admin)
def adminapp_doctor_list(request):
    doctors = DoctorProfile.objects.all()
    context = {
        'doctors': doctors,
    }
    return render(request, 'adminapp/doctor-list.html', context)


@login_required(login_url='adminapp_login')
@user_passes_test(is_admin)
def adminapp_patient_list(request):
    patients = PatientProfile.objects.all()
    context = {
        'patients': patients,
    }
    return render(request, 'adminapp/patient-list.html', context)


def change_status(request):
    doc_id = request.GET.get('doctor_id')
    status = request.GET.get('is_active')
    try:
        doctor = User.objects.get(id=doc_id)
        if doctor:
            if status=='true':
                doctor.is_active = True
            elif status=='false':
                doctor.is_active = False
            doctor.save()

            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'message': 'Doctor not found'})
    except User.DoesNotExist:
        return JsonResponse({'success': False, 'message': 'Doctor not found'})
    

@login_required(login_url='adminapp_login')
@user_passes_test(is_admin)
def adminapp_specialities(request):
    if request.method == 'POST':
        name = request.POST['specialization']
        image = request.FILES['image']
        slug = slugify(name)
        try:
            specialization = Specialization(
                name=name,
                slug=slug,
                image=image,                
            )
            specialization.save()
            messages.success(request, 'Specialization saved successfully.')
        except Exception as e:
            messages.error(request, f'Error saving specialization: {e}')
    specializations = Specialization.objects.all()
    context = {
        'specializations': specializations,
    }
    return render(request, 'adminapp/specialities.html', context)


def delete_specialization(request):
    if request.method == 'POST':
        spz_id = request.POST['specialization_id']
        try:
            specialization = Specialization.objects.get(id=spz_id)
            specialization.delete()
            messages.success(request, 'Specialization deleted successfully.')
        except Exception as e:
            messages.error(request, f'Error deleting specialization: {e}')
        return redirect('adminapp_specialities')


@login_required(login_url='adminapp_login')
@user_passes_test(is_admin)
def edit_specialization(request):
    if request.method == 'POST':
        spz_id = request.POST['specialization_id']
        name = None
        image = None
        if 'specialization' in request.POST:
            name = request.POST['specialization']
        if 'image' in request.FILES:
            image = request.FILES['image']

        try:
            specialization = Specialization.objects.get(id=spz_id)
            if name:
                specialization.name = name
            if image:
                specialization.image = image
            specialization.save()
            messages.success(request, 'Specialization updated successfully.')
        except Exception as e:
            messages.error(request, f'Error editing specialization: {e}')
        return redirect('adminapp_specialities')
    

@login_required(login_url='adminapp_login')
@user_passes_test(is_admin)
def adminapp_reviews(request):
    reviews = ReviewRating.objects.all().order_by('-updated_at')
    context = {
        'reviews': reviews,
    }

templates/adminapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>HealthMate - Admin</title>
		
		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">
		
		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'assets_admin/css/bootstrap.min.css' %}">
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{% static 'assets_admin/css/font-awesome.min.css' %}">
		
		<!-- Feathericon CSS -->
        <link rel="stylesheet" href="{% static 'assets_admin/css/feathericon.min.css' %}">		
		
		<!-- Main CSS -->
        <link rel="stylesheet" href="{% static 'assets_admin/css/style.css' %}">
		
    </head>

    <body>	
		<!-- Main Wrapper -->
        <div class="main-wrapper">

            <!-- Header -->
            <div class="header">

                <!-- Logo -->
                <div class="header-left">
                    <a href="{% url 'index' %}" class="logo">
                        <img src="{% static 'assets/img/logo.png' %}" alt="Logo" style="width:170px;">
                    </a>
                    <a href="{% url 'index' %}" class="logo logo-small">
                        <img src="{% static 'assets/img/favicon.png' %}" alt="Logo" width="30" height="30">
                    </a>
                </div>
                <!-- /Logo -->
                
                <a href="javascript:void(0);" id="toggle_btn">
                    <i class="fe fe-text-align-left"></i>
                </a>
                
                
                <!-- Mobile Menu Toggle -->
                <a class="mobile_btn" id="mobile_btn">
                    <i class="fa fa-bars"></i>
                </a>
                <!-- /Mobile Menu Toggle -->
                
                <!-- Header Right Menu -->
                <ul class="nav user-menu">
                    
                    <!-- User Menu -->
                    <li class="nav-item dropdown has-arrow">
                        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                            <span class="user-img"><img class="rounded-circle" src="{{user.profile_picture.url}}" width="31" alt="{{user.get_full_name}}"></span>
                        </a>
                        <div class="dropdown-menu">
                            <div class="user-header">
                                <div class="avatar avatar-sm">
                                    <img src="{{user.profile_picture.url}}" alt="User Image" class="avatar-img rounded-circle">
                                </div>
                                <div class="user-text">
                                    <h6>{{user.get_full_name}}</h6>
                                    <p class="text-muted mb-0">Administrator</p>
                                </div>
                            </div>
                            <a class="dropdown-item" href="{% url 'adminapp_profile' %}">My Profile</a>
                            <a class="dropdown-item" href="{% url 'adminapp_logout' %}">Logout</a>
                        </div>
                    </li>
                    <!-- /User Menu -->
                    
                </ul>
                <!-- /Header Right Menu -->
                
            </div>
            <!-- /Header -->
                        
            <!-- Sidebar -->
            <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
                    <div id="sidebar-menu" class="sidebar-menu">
                        <ul>
                            <li class="menu-title"> 
                                <span>Main</span>
                            </li>
                            <li class="{% if '/adminapp/' == request.path %}active{% endif %}"> 
                                <a href="{% url 'index' %}"><i class="fe fe-home"></i> <span>Dashboard</span></a>
                            </li>
                            <li class="{% if '/adminapp/lab_appointments/' == request.path or '/adminapp/edit_lab_appointments/' in request.path%}active{% endif %}"> 
                                <a href="{% url 'adminapp_lab_appointments' %}"><i class="fe fe-layout"></i> <span>Lab Appointments</span></a>
                            </li>
                            <li class="{% if '/adminapp/lab_tests/' == request.path %}active{% endif %}"> 
								<a href="{% url 'adminapp_lab_tests' %}"><i class="fe fe-vector"></i> <span>Lab Tests</span></a>
							</li>
                            <li class="{% if '/adminapp/specialities/' == request.path %}active{% endif %}"> 
                                <a href="{% url 'adminapp_specialities'%}"><i class="fe fe-users"></i> <span>Specialities</span></a>
                            </li>
                            <li class="{% if '/adminapp/doctor_list/' == request.path %}active{% endif %}"> 
                                <a href="{% url 'adminapp_doctor_list'%}"><i class="fe fe-user-plus"></i> <span>Doctors</span></a>
                            </li>
                            <li class="{% if '/adminapp/patient_list/' == request.path %}active{% endif %}"> 
                                <a href="{% url 'adminapp_patient_list'%}"><i class="fe fe-user"></i> <span>Patients</span></a>
                            </li>
                            <li class="{% if '/adminapp/reviews/' == request.path %}active{% endif %}"> 
                                <a href="{% url 'adminapp_reviews' %}"><i class="fe fe-star-o"></i> <span>Reviews</span></a>
                            </li>
                            <li class="{% if '/adminapp/transactions/' == request.path %}active{% endif %}"> 
                                <a href="{% url 'adminapp_transactions' %}"><i class="fe fe-activity"></i> <span>Transactions</span></a>
                            </li>
                            <li class="menu-title"> 
                                <span>Pages</span>
                            </li>
                            <li class="{% if '/adminapp/profile/' == request.path %}active{% endif %}"> 
                                <a href="{% url 'adminapp_profile' %}"><i class="fe fe-user-plus"></i> <span>Profile</span></a>
                            </li>
                            <li class="submenu">
                                <a href="#"><i class="fe fe-document"></i> <span> Authentication </span> <span class="menu-arrow"></span></a>
                                <ul style="display: none;">
                                    <li><a href="{% url 'adminapp_login' %}"> Login </a></li>
                                    <li><a href="{% url 'adminapp_register' %}"> Register </a></li>
                                    <li><a href="#"> Forgot Password </a></li>
                                    <li><a href="{% url 'adminapp_logout' %}"> Logout </a></li>
                                </ul>
                            </li>                                                        
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /Sidebar -->
            
            {% block pagecontent %}
            {% endblock %}

        </div>
		<!-- /Main Wrapper -->
		
		<!-- jQuery -->
        <script src="{% static 'assets_admin/js/jquery-3.2.1.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="{% static 'assets_admin/js/popper.min.js' %}"></script>
        <script src="{% static 'assets_admin/js/bootstrap.min.js' %}"></script>
		
		<!-- Slimscroll JS -->
        <script src="{% static 'assets_admin/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>		
		
		<!-- Custom JS -->
		<script  src="{% static 'assets_admin/js/script.js' %}"></script>
		
        <script>
            setTimeout(function(){
                $('#mess').fadeOut('slow')
            }, 4000)
        </script>

    </body>

</html>

templates/adminapp/lab-tests.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block pagecontent %}

<!-- Page Wrapper -->
<div class="page-wrapper">
    <div class="content container-fluid">
    
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Lab Tests</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Lab Tests</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        {% include 'includes/alerts.html' %}
        <div class="row">
            
            <div class="col-12">
                
                <!-- General -->
                
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">General</h4>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'adminapp_lab_tests' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_name">Test Name</label>
                                    {{form.name}}
                                </div>                                
                                <div class="form-group">
                                    <label for="id_description">Description</label>
                                    {{form.description}}
                                    <small class="text-secondary">Write test <b>description</b> here</small><br>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label for="id_price">Price</label>
                                            {{form.price}}
                                            <small class="text-secondary">Enter price in <b>INR(₹)</b></small>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="id_image">Test Image</label>
                                            {{form.image}}
                                            <small class="text-secondary">Recommended image size is <b>150px x 150px</b></small>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col text-right">
                                        <button type="submit" class="btn btn-primary">Add Lab Test</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                
                <!-- /General -->
                    
            </div>
        </div>
        

        <div class="row">
            {% for test in tests %}
            <div class="col-12 col-md-4 col-lg-3 d-flex">
                <div class="card flex-fill">
                    <img alt="Card Image" src="{{test.image.url}}" class="card-img-top">
                    <div class="card-header">
                        <h5 class="card-title mb-0">{{test.name}}</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text mb-1">{{test.description}}</p>
                        <p class="card-text mb-1"><b>Price:</b> ₹{{test.price}}</p>                        
                    </div>
                    <div class="card-footer">
                        <form action="{% url 'delete_lab_tests' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="lab_test_id" value="{{test.id}}">
                            <button type="submit" class="btn btn-sm bg-danger-light"><i class="fe fe-trash"></i> Delete</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>			
</div>
<!-- /Page Wrapper -->

{% endblock %}

templates/adminapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>HealthMate - Login</title>
		
		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">

		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'assets_admin/css/bootstrap.min.css' %}">
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{% static 'assets_admin/css/font-awesome.min.css' %}">
		
		<!-- Main CSS -->
        <link rel="stylesheet" href="{% static 'assets_admin/css/style.css' %}">
		
    </head>
    <body>
	
		<!-- Main Wrapper -->
        <div class="main-wrapper login-body">
            <div class="login-wrapper">
            	<div class="container">
                	<div class="loginbox">
                    	<div class="login-left">
							<img class="img-fluid" src="{% static 'assets/img/logo-white.png' %}" alt="Logo">
                        </div>
                        <div class="login-right">
							<div class="login-right-wrap">
								<h1>Login</h1>
								{% include 'includes/alerts.html' %}
								<p class="account-subtitle">Access to our dashboard</p>
								
								<!-- Form -->
								<form action="{% url 'adminapp_login' %}" method="POST">
									{%csrf_token%}
									<div class="form-group">
										<input class="form-control" type="text" placeholder="Email" name="email">
									</div>
									<div class="form-group">
										<input class="form-control" type="password" placeholder="Password" name="password">
									</div>
									<div class="form-group">
										<button class="btn btn-primary btn-block" type="submit">Login</button>
									</div>
								</form>
								<!-- /Form -->
								
								<div class="text-center forgotpass"><a href="forgot-password.html">Forgot Password?</a></div>
								<div class="login-or">
									<span class="or-line"></span>
									<span class="span-or">or</span>
								</div>								  
								
								<div class="text-center dont-have">Don’t have an account? <a href="{% url 'adminapp_register' %}">Register</a></div>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
		<!-- /Main Wrapper -->
		
		<!-- jQuery -->
        <script src="{% static 'assets_admin/js/jquery-3.2.1.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="{% static 'assets_admin/js/popper.min.js' %}"></script>
        <script src="{% static 'assets_admin/js/bootstrap.min.js' %}"></script>
		
		<!-- Custom JS -->
		<script src="{% static 'assets_admin/js/script.js' %}"></script>
		
		<script>
            setTimeout(function(){
                $('#mess').fadeOut('slow')
            }, 4000)
        </script>

    </body>

</html>

templates/adminapp/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on the link below to reset your password.
http://{{domain}}{% url 'resetAdminpassword_validate' uidb64=uid token=token %}

If you think its not you please ignore this email.

Note: This e-mail is sent for testing purpose of college project "HealthMate: Online Doctor Consultation". If you are not directly familiar with the student developers kindly block this email.

Thanks
Abhishek Rai

{% endautoescape %}